<?php
/** Template Name: ShanYing · 说说 */
if(!defined('ABSPATH'))exit;
get_header();while(have_posts()):the_post();$talks=feng_talk_list(); ?>
<section class="feng-talks xf-container" data-feng-talks data-endpoint="<?php echo esc_url(admin_url('admin-ajax.php')); ?>" data-page-url="<?php echo esc_url(get_permalink()); ?>" data-upload-limit="<?php echo (int)feng_talk_upload_limit(); ?>" data-upload-total="<?php echo (int)feng_talk_total_limit(); ?>" data-upload-label="<?php echo esc_attr(size_format(feng_talk_upload_limit())); ?>">
 <header class="feng-unified-heading"><h1><i class="fa-solid fa-comment-dots feng-page-title-icon" aria-hidden="true"></i><?php the_title(); ?></h1><small data-talk-total><?php echo (int)$talks['total']; ?> 条</small></header>
 <div class="feng-talk-introduction"><p>不必写成一篇文章，也值得留在这里。</p><?php feng_activity_calendar('feng_talk',0,array('days'=>180,'rows'=>5,'hide_heading'=>true,'hide_footer'=>true)); ?></div>
 <?php if(trim(get_the_content())): ?><div class="xf-prose feng-talk-intro"><?php the_content(); ?></div><?php endif; ?>
 <div class="feng-talk-filter" data-talk-filter hidden><span data-talk-filter-label></span><button type="button" data-talk-clear>查看全部 <?php echo feng_icon('close'); ?></button></div>
 <div class="feng-talk-board" data-talk-board><?php echo $talks['html']; ?></div>
 <div class="feng-talk-empty" data-talk-empty <?php if($talks['total'])echo 'hidden'; ?>><?php echo feng_icon('comment'); ?><h2>留一张生活的便签</h2><p>一些念头，一张照片，或者今天的小事。</p><p>登录后，点击下方加号写第一条说说。</p></div>
 <div class="feng-talk-more"><button type="button" class="xf-glass-link" data-talk-more <?php if(!$talks['more'])echo 'hidden'; ?>>再翻一些 <?php echo feng_icon('arrow-down'); ?></button></div>
 <nav class="feng-talk-dock" aria-label="说说工具"><strong>说说<span></span></strong><button type="button" data-talk-filter-toggle aria-label="筛选关键词" aria-expanded="false" aria-controls="feng-talk-tags"><?php echo feng_icon('hash'); ?></button><button type="button" data-talk-create aria-label="发布说说" hidden><?php echo feng_icon('plus'); ?></button><a data-talk-login href="<?php echo esc_url(wp_login_url(get_permalink())); ?>" aria-label="登录后发布说说"><?php echo feng_icon('person'); ?></a><button type="button" data-talk-layout aria-label="切换为整齐排列" aria-pressed="false"><?php echo feng_icon('grid'); ?></button><span data-talk-dock-count><?php echo (int)$talks['total']; ?> 条</span></nav>
 <aside id="feng-talk-tags" class="feng-talk-tag-picker" data-talk-tags hidden aria-label="关键词筛选"><header><strong>按关键词看看</strong><button type="button" data-talk-filter-close aria-label="关闭关键词筛选"><?php echo feng_icon('close'); ?></button></header><div data-talk-tag-list></div></aside>
 <p class="feng-talk-notice" data-talk-notice role="status" aria-live="polite" hidden><span></span><button type="button" data-talk-undo hidden>撤销删除</button><button type="button" data-talk-notice-close aria-label="关闭提示"><?php echo feng_icon('close'); ?></button></p>
 <dialog class="feng-talk-dialog" data-talk-detail aria-labelledby="feng-talk-detail-title"><div class="feng-talk-detail-head"><div><p>生活的便签</p><h2 id="feng-talk-detail-title">这一刻</h2></div><button type="button" data-talk-close aria-label="关闭说说"><?php echo feng_icon('close'); ?></button></div><div class="feng-talk-detail-tags" data-talk-detail-tags></div><p class="feng-talk-detail-content" data-talk-detail-content></p><div class="feng-talk-detail-images" data-talk-detail-images></div><footer class="feng-talk-detail-foot"><span data-talk-detail-meta></span><div data-talk-manage hidden><button type="button" data-talk-edit><?php echo feng_icon('edit'); ?> 编辑</button><button type="button" data-talk-delete><?php echo feng_icon('trash'); ?> 删除</button></div></footer><div class="feng-talk-delete-confirm" data-talk-delete-confirm hidden><p>将这条说说移入回收站？</p><button type="button" data-talk-delete-cancel>先留着</button><button type="button" data-talk-delete-confirm-button>确认删除</button></div></dialog>
 <dialog class="feng-talk-dialog feng-talk-compose" data-talk-compose aria-labelledby="feng-talk-compose-title"><header><div><p>留住一个小小的瞬间</p><h2 id="feng-talk-compose-title">写条说说</h2></div><button type="button" data-talk-close aria-label="关闭编辑"><?php echo feng_icon('close'); ?></button></header><form data-talk-form enctype="multipart/form-data">
 <label class="screen-reader-text" for="feng-talk-content">说说正文</label><textarea id="feng-talk-content" name="content" maxlength="4000" placeholder="此刻，想说点什么？" rows="7"></textarea><div class="feng-talk-word-count"><span data-talk-words>0</span> / 4000</div>
 <label class="feng-talk-field" for="feng-talk-keywords"><span><?php echo feng_icon('hash'); ?> 关键词</span><input id="feng-talk-keywords" name="tags" placeholder="生活，随想… 用逗号分隔，最多 4 个" maxlength="100"></label><div class="feng-talk-suggestions" data-talk-suggestions></div>
 <label class="feng-talk-field" for="feng-talk-location"><span><?php echo feng_icon('pin'); ?> 地点</span><input id="feng-talk-location" name="location" placeholder="可选，手动写下城市或地点" maxlength="60"></label>
 <div class="feng-talk-upload-preview" data-talk-upload-preview></div><div class="feng-talk-form-error" data-talk-form-error role="alert"></div><footer><label class="feng-talk-add-image" for="feng-talk-images"><?php echo feng_icon('image'); ?> 添加图片<input id="feng-talk-images" name="images[]" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple></label><small>最多 4 张 · 单张 <?php echo esc_html(size_format(feng_talk_upload_limit())); ?></small><button type="submit" data-talk-submit><?php echo feng_icon('arrow-up-right'); ?><span>发布</span></button></footer>
 </form><div class="feng-talk-discard" data-talk-discard hidden><p>还有未保存的内容，要继续编辑还是放弃？</p><button type="button" data-talk-continue>继续编辑</button><button type="button" data-talk-discard-confirm>放弃修改</button></div></dialog>
 <noscript><p>可以直接浏览说说。发布、筛选和展开卡片需要开启 JavaScript。</p></noscript>
</section>
<?php endwhile;get_footer(); ?>
